# Uncomment the next line to define a global platform for your project
#platform :ios, '12.0'

plugin 'cocoapods-embed-flutter'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Flutter'
  pod 'fluttertoast', :path => '../packages/fluttertoast-8.2.1/ios'
  pod 'flutter_barcode_scanner', :path => '../packages/flutter_barcode_scanner/ios'
  pod 'path_provider', :path => '../packages/path_provider/ios'


end
