# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

plugin 'cocoapods-embed-flutter'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Flutter'
  pod 'fluttertoast', :path => '../packages/fluttertoast-8.2.1/ios'
  pod 'flutter_barcode_scanner', :path => '../packages/flutter_barcode_scanner/ios'
  pod 'flutter_inappwebview', :path => '../packages/flutter_inappwebview/ios'
  pod 'url_launcher_ios', :path => '../packages/url_launcher_ios-6.1.2/ios'
  pod 'webview_flutter_wkwebview', :path => '../packages/webview_flutter_wkwebview-3.2.1/ios'


end
